# Lab 2: Comparación de modelos

## ¡Bienvenido/a!

Te invitamos a realizar el primer trabajo.
- Objetivo: comparar modelos de regresión y clasificación en Python.
- Tipo de actividad: Individual
- Tipo de evaluación: Sumativa 
- Ponderación: 12%
- Puntaje: 100 puntos
- Calificación: Escala de 1 a 7, con una exigencia de 50%. La nota mínima para aprobar es 4.0.

### Objetivo

El propósito de esta tarea es profundizar en los conceptos de validación cruzada en los contextos de regresión y clasificación. Asimismo, se pretende que el estudiante comprenda la relevancia de la selección y comparación de modelos en la resolución de problemas de aprendizaje automático.

En el caso del problema de la regresión, se llevará a cabo una comparación entre la regresión lineal, el k-NN y los árboles de regresión. Para el problema de clasificación, se realizará una comparación entre la regresión logística, el k-NN y los árboles de clasificación.

In [1]:
# Módulos básicos para análisis y manipulación de datos
import numpy as np
import pandas as pd

# Modelos de regresión y clasificación
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier

# Preprocesamiento de datos
from sklearn.preprocessing import MinMaxScaler

# Módulos para evaluación de modelos
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn import metrics

# Bases de datos del Lab
import faraway.datasets.ozone as ozone
import faraway.datasets.prostate as prostate 

# Problema 1

Responda a las siguientes preguntas utilizando el conjunto de datos ozone. Considere $O^3$ como variable respuesta, mientras que las demás variables serán consideradas como variables explicativas

In [2]:
ozone_data = ozone.load()  # El objeto data contiene los datos para el problema 1

In [3]:
ozone_data

O3    vh  wind  humidity  temp   ibh  dpg  ibt  vis  doy
0     3  5710     4        28    40  2693  -25   87  250   33
1     5  5700     3        37    45   590  -24  128  100   34
2     5  5760     3        51    54  1450   25  139   60   35
3     6  5720     4        69    35  1568   15  121   60   36
4     4  5790     6        19    45  2631  -33  123  100   37
..   ..   ...   ...       ...   ...   ...  ...  ...  ...  ...
325   8  5630     4        50    50  2851   -5  100   70  384
326   2  5730     3        53    51   111  -14  225  200  387
327   3  5690     3        23    51  5000  -36  107   70  388
328   5  5650     3        61    50  3704   18   83   40  389
329   1  5550     4        85    39  5000    8   44  100  390

[330 rows x 10 columns]

1.1 - Realizar una descomposición aleatoria de la base de datos con la proporción 70%-30% para train y test, respectivamente. Utilice el número 111 como semilla de aleatorización.

Guardar la información en los siguientes objetos:
- `train`: partición de entrenamiento    (incluyendo todas las variables).
- `test`: partición para la validacíon   (incluyendo todas las variables).

Recuerde respetar la semilla de aleatorización, la proporción de la partición y el nombre de los objetos. Además, utilice `train_test_split(ozone_data, ...)` para obtener de inmediato las particiones de entrenamiento y validación con todas las variables.

In [ ]:
train = None      # Variable que debe modificar
test = None       # Variable que debe modificar

# your code here
raise NotImplementedError

In [10]:
train, test = train_test_split(ozone_data, test_size=0.3, random_state=111)
print(f"train: {train.shape}")
print(f"test: {test.shape}")


train: (231, 10)
test: (99, 10)


In [5]:
# Test 1 - P 1.1

In [6]:
# Test 2 - P 1.1

1.2 - Utilizando la partición de entrenamiento, ajuste los siguientes modelos:
- Regresión lineal múltiple con intercepto.
- k-NN con $k=10$ (`n_neighbors=10`) y utilizando como métrica la distancia euclidiana (`metric='euclidean'`). Para este modelo, además, estandarizar las variables utilizando el método min-max (`MinMaxScaler()`).
- Árbol de regresión con profundidad máxima de 4 (`max_depth=4`) y número mínimo para realizar una partición en 20 (`min_samples_split=20`). Además, utilice la semilla de aleatorización 123 (`random_state=123`).

Luego de ajustar los modelos, calcule el error cuadrático medio (MSE) de cada uno de ellos sobre la partición de entrenamiento, el cual 
representará que tan bien se ajusta el modelo a los datos de entrenamiento, y el error cuadrático medio sobre la partición de validación, el cual representará la capacidad de predicción y generalización del modelo.

Recuerde que el MSE se calcula como:
$$
MSE = \frac{1}{n}\sum_{i=1}^n (y_i - \hat{y}_i)^2
$$
donde $y_i$ es el valor real de la variable respuesta y $\hat{y}_i$ es el valor predicho por el modelo.

Para esta pregunta, se espera que usted entregue dos vectores de largo 3, uno para el MSE de entrenamiento y otro para el MSE de validación. El primer elemento de cada vector corresponde al MSE de la regresión lineal, el segundo elemento corresponde al MSE del k-NN y el tercer elemento corresponde al MSE del árbol de regresión. 

Los nombres de los vectores deben ser `mse_train` y `mse_test`, respectivamente.

In [ ]:
mse_train = None       # Variable que debe modificar
mse_test = None        # Variable que debe modificar

# your code here
raise NotImplementedError

In [7]:
X_train = train.drop(columns='O3')
y_train = train['O3']
X_test = test.drop(columns='O3')
y_test = test['O3']

#regresion 
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)
y_train_pred_linear = linear_model.predict(X_train)
y_test_pred_linear = linear_model.predict(X_test)
mse_train_linear = metrics.mean_squared_error(y_train, y_train_pred_linear)
mse_test_linear = metrics.mean_squared_error(y_test, y_test_pred_linear)


#knn
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
knn_model = KNeighborsRegressor(n_neighbors=10, metric='euclidean')
knn_model.fit(X_train_scaled, y_train)
y_train_pred_knn = knn_model.predict(X_train_scaled)
y_test_pred_knn = knn_model.predict(X_test_scaled)
mse_train_knn = metrics.mean_squared_error(y_train, y_train_pred_knn)
mse_test_knn = metrics.mean_squared_error(y_test, y_test_pred_knn)


# Arbol
tree_model = DecisionTreeRegressor(max_depth=4, min_samples_split=20, random_state=123)
tree_model.fit(X_train, y_train)
y_train_pred_tree = tree_model.predict(X_train)
y_test_pred_tree = tree_model.predict(X_test)

# Calcular el MSE
mse_train_tree = metrics.mean_squared_error(y_train, y_train_pred_tree)
mse_test_tree = metrics.mean_squared_error(y_test, y_test_pred_tree)
mse_train = [mse_train_linear, mse_train_knn, mse_train_tree]
mse_test = [mse_test_linear, mse_test_knn, mse_test_tree]


print(f"MSE en el conjunto de entrenamiento: {mse_train}")
print(f"MSE en el conjunto de validación: {mse_test}")

MSE en el conjunto de entrenamiento: [18.458600661024605, 14.193722943722946, 11.919003538397622]
MSE en el conjunto de validación: [21.268081965406097, 18.202727272727273, 21.754927466213918]


In [ ]:
# Test 1 - P 1.2

In [ ]:
# Test 2 - P 1.2

1.3 - Con los resultados obtenidos en la pregunta anterior: ¿qué modelo debería elegir?. Base su respuesta en el error cuadrático medio tanto para la partición de entrenamiento como de validación.

Para responder esta pregunta, debe entregar un string con el nombre `best_model_train` para la elección utilizando la muestra de entrenamiento y otro con el nombre `best_model_test` para la elección con la muestra de validación, estos string deben contener el nombre del modelo elegido. 

Los nombres de los modelos en el string pueden ser los siguientes: "LM", "k-NN" y "DTree" para la regresión lineal, k-NN y árbol de regresión, respectivamente. Por ejemplo, si el modelo elegido es la regresión lineal, entonces debe entregar el string "LM".

Además, responda, en el string `Interpretacion` una de las siguientes alternativas:
- "Como los modelos difieren se prefiere utilizar el modelo escogido con la muestra de validación ya que tiene menos posibilidad de caer en un sobreajuste."
- "Como los modelos difieren se prefiere utilizar el modelo escogido con la muestra de entrenamiento ya que se ajusta mejor a los datos."
- "En ambos casos se escoge el mismo modelo."

In [ ]:
best_model_train = None      # Variable que debe modificar
best_model_test = None       # Variable que debe modificar
Interpretacion = None        # Variable que debe modificar

# your code here
raise NotImplementedError

In [14]:
#train
min_mse_train = min(mse_train)
best_model_train_index = mse_train.index(min_mse_train)
modelos = ["LM", "k-NN", "DTree"]
best_model_train = modelos[best_model_train_index]

# test
min_mse_test = min(mse_test)
best_model_test_indice = mse_test.index(min_mse_test)
best_model_test = modelos[best_model_test_indice]

if best_model_train == best_model_test:
    Interpretacion = "En ambos casos se escoge el mismo modelo."
elif best_model_test == best_model_train:
    Interpretacion = "Como los modelos difieren se prefiere utilizar el modelo escogido con la muestra de validación ya que tiene menos posibilidad de caer en un sobreajuste."
else:
    Interpretacion = "Como los modelos difieren se prefiere utilizar el modelo escogido con la muestra de entrenamiento ya que se ajusta mejor a los datos."

print(f"Modelo elegido para entrenamiento: {best_model_train}")
print(f"Modelo elegido para validación: {best_model_test}")
print(f"Interpretación: {Interpretacion}")


Modelo elegido para entrenamiento: DTree
Modelo elegido para validación: k-NN
Interpretación: Como los modelos difieren se prefiere utilizar el modelo escogido con la muestra de entrenamiento ya que se ajusta mejor a los datos.


In [ ]:
# Test 1 - P 1.3

In [ ]:
# Test 2 - P 1.3

In [ ]:
# Test 3 - P 1.3

1.4 - Utilizando la partición de entrenamiento, realice una validación cruzada k-fold con $k=5$ para cada uno de los modelos de la pregunta anterior. Utilice el MSE como métrica de desempeño. Debe reportar el error cuadrático medio promedio y la desviación estándar del error cuadrático medio para cada modelo. Utilice la función `cross_val_score` para realizar la validación cruzada k-fold.

Se espera que usted entregue dos vectores de largo 3, uno para el MSE promedio y otro para la desviación estándar del MSE. El primer elemento de cada vector corresponde al MSE de la regresión lineal, el segundo elemento corresponde al MSE del k-NN y el tercer elemento corresponde al MSE del árbol de decisión.

El nombre de los vectores deben ser `mse_cv_mean` y `mse_cv_std`, respectivamente.

La desviación estándar del MSE será utilizada para determinar la variabilidad del error de predicción del modelo. Por lo tanto, un modelo con menor desviación estándar del MSE será preferible. Esta medida de variabilidad es importante, ya que nos permite determinar si el modelo es robusto o no. Ya que si el modelo es robusto, entonces el error de predicción no variará mucho al cambiar la partición de entrenamiento. En caso contrario, cuando los modelos están sobreajustados, el error de predicción variará mucho al cambiar la partición de entrenamiento.


**Observación**: En el caso del k-vecino más cercano "k-NN" determine mediante la validación cruzada el número de vecinos óptimos utilizado el MSE como medida de error y como métrica la distancia "euclidiana" de las variables de entrada estandarizadas por MinMax. Guarde el número de vecinos en `K` donde la búsqueda del óptimo se realiza en la grilla de 1 a 15, es decir, K debe ser un valor entero entre 1 y 15.

Para los otros métodos debe utilizar los mismos parámetros de la pregunta anterior, es decir, la profundidad máxima del árbol debe ser 4 y el número mínimo para realizar una partición debe ser 20. Además, debe utilizar la semilla de aleatorización 123 como parámetro del modelo de árbol de regresión (`random_state=123`).

In [ ]:
mse_cv_mean = None       # Variable que debe modificar
mse_cv_std = None        # Variable que debe modificar
K = None                 # Variable que debe modificar

# your code here
raise NotImplementedError

In [16]:
from sklearn.model_selection import GridSearchCV

In [40]:
from sklearn.model_selection import GridSearchCV
mse_scorer = metrics.make_scorer(metrics.mean_squared_error)
#regrsesion
lm_model = LinearRegression()
mse_lm = cross_val_score(lm_model, X_train, y_train, cv=5, scoring=mse_scorer)

# knn
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
knn_model = KNeighborsRegressor(metric='euclidean')
param_grid = {'n_neighbors': np.arange(1, 16)}
grid_search = GridSearchCV(knn_model, param_grid, cv=5, scoring=mse_scorer)
grid_search.fit(X_train_scaled, y_train)

K = grid_search.best_params_['n_neighbors']  
knn_best_model = grid_search.best_estimator_
mse_knn = cross_val_score(knn_best_model, X_train_scaled, y_train, cv=5, scoring=mse_scorer)

# arbol
dtree_model = DecisionTreeRegressor(max_depth=4, min_samples_split=20, random_state=123)
mse_dtree = cross_val_score(dtree_model, X_train, y_train, cv=5, scoring=mse_scorer)


mse_cv_mean = [
    mse_lm.mean(),  
    mse_knn.mean(), 
    mse_dtree.mean()  
]

mse_cv_std = [
    mse_lm.std(),  
    mse_knn.std(),   
    mse_dtree.std()  
]

print(f"mejor k: {K}")
print(f"mse_cv_mean: {mse_cv_mean}")
print(f"mse_cv_std: {mse_cv_std}")

mejor k: 1
mse_cv_mean: [21.314104479566375, 25.908880666049953, 25.14949524061326]
mse_cv_std: [3.6466254107281197, 2.4211377889472185, 2.7788102754373085]


In [24]:
mse_scorer = metrics.make_scorer(metrics.mean_squared_error, greater_is_better=False)
lm_model = LinearRegression()
mse_lm = cross_val_score(lm_model, X_train, y_train, cv=5, scoring=mse_scorer)
best_k = None
best_mse_knn = float('inf')
mse_knn_list = []
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)

for k in range(1, 16):
    knn_model = KNeighborsRegressor(n_neighbors=k, metric='euclidean')
    mse_knn = cross_val_score(knn_model, X_train_scaled, y_train, cv=5, scoring=mse_scorer)
    mse_knn_mean = -mse_knn.mean()  
    mse_knn_list.append(mse_knn_mean)
    
    if mse_knn_mean < best_mse_knn:
        best_mse_knn = mse_knn_mean
        best_k = k

knn_best_model = KNeighborsRegressor(n_neighbors=best_k, metric='euclidean')
mse_knn_final = cross_val_score(knn_best_model, X_train_scaled, y_train, cv=5, scoring=mse_scorer)
dtree_model = DecisionTreeRegressor(max_depth=4, min_samples_split=20, random_state=123)
mse_dtree = cross_val_score(dtree_model, X_train, y_train, cv=5, scoring=mse_scorer)
mse_cv_mean = [
    -mse_lm.mean(),  
    -mse_knn_final.mean(),  
    -mse_dtree.mean()  
]

mse_cv_std = [
    mse_lm.std(),  
    mse_knn_final.std(),  
    mse_dtree.std()  
]

print(f"K: {best_k}")
print(f"mse_cv_mean: {mse_cv_mean}")
print(f"mse_cv_std: {mse_cv_std}")


K: 10
mse_cv_mean: [21.314104479566375, 17.0750092506938, 25.14949524061326]
mse_cv_std: [3.6466254107281197, 2.321109454594844, 2.7788102754373085]


In [ ]:
# Test 1 - P 1.4

In [ ]:
# Test 2 - P 1.4

In [ ]:
# Test 3 - P 1.4

1.5 - Según los resultados obtenidos en la pregunta anterior, ¿qué modelo debería elegir?. Base su respuesta en el error cuadrático medio promedio de la validación cruzada. 

Además, para el modelo seleccionado cuantificar el error de generalización mediante el RMSE.

Recuerde que el RMSE se calcula como:
$$
RMSE = \sqrt{MSE}=\sqrt{\frac{1}{m}\sum_{i=1}^{m}e_i^2},\quad\text{donde}\quad e_i=y_i-\hat{y}_i,~~i=1,\dots,m.
$$


Para responder esta pregunta, debe entregar un string con el nombre `best_model_cv` que corresponda al nombre del modelo elegido, mientras que el error de generalización medido a través del RMSE debe quedar guardado en `best_rmse_test`. 

Los nombres de los modelos en el string deben ser los siguientes: "LM", "k-NN" y "DTree" para la regresión lineal, k-NN y árbol de regresión, respectivamente. 

In [ ]:
best_model_cv = None       # Variable que debe modificar
best_rmse_test = None      # Variable que debe modificar

# your code here
raise NotImplementedError

In [30]:
mse_scorer = metrics.make_scorer(metrics.mean_squared_error, greater_is_better=False)
#modelo lineal
lm_model = LinearRegression()
mse_lm_cv = cross_val_score(lm_model, X_train, y_train, cv=5, scoring=mse_scorer)
mse_lm_mean = -mse_lm_cv.mean()  
mse_lm_std = mse_lm_cv.std()

#knn
knn_model = KNeighborsRegressor(n_neighbors=10, metric='euclidean')
mse_knn_cv = cross_val_score(knn_model, X_train_scaled, y_train, cv=5, scoring=mse_scorer)
mse_knn_mean = -mse_knn_cv.mean()  
mse_knn_std = mse_knn_cv.std()

#arbol
dtree_model = DecisionTreeRegressor(max_depth=4, min_samples_split=20, random_state=123)
mse_dtree_cv = cross_val_score(dtree_model, X_train, y_train, cv=5, scoring=mse_scorer)
mse_dtree_mean = -mse_dtree_cv.mean()  
mse_dtree_std = mse_dtree_cv.std()


mse_cv_mean = [mse_lm_mean, mse_knn_mean, mse_dtree_mean]
mse_cv_std = [mse_lm_std, mse_knn_std, mse_dtree_std]
print(f"mse_cv_mean: {mse_cv_mean}")
print(f"mse_cv_std: {mse_cv_std}")


modelos= ["LM", "k-NN", "DTree"]
best_model_cv_index = np.argmin(mse_cv_mean)
best_model_cv = modelos[best_model_cv_index]


if best_model_cv == "LM":
    best_model = LinearRegression()
elif best_model_cv == "k-NN":
    best_model = KNeighborsRegressor(n_neighbors=10, metric='euclidean')
    X_test_scaled = scaler.transform(X_test)  
else:
    best_model = DecisionTreeRegressor(max_depth=4, min_samples_split=20, random_state=123)

best_model.fit(X_train, y_train)
y_pred = best_model.predict(X_test)
mse_test = metrics.mean_squared_error(y_test, y_pred)
best_rmse_test = np.sqrt(mse_test)


print(f"best_model_cv: {best_model_cv}")
print(f"best_rmse_test: {best_rmse_test}")


mse_cv_mean: [21.314104479566375, 17.0750092506938, 25.14949524061326]
mse_cv_std: [3.6466254107281197, 2.321109454594844, 2.7788102754373085]
best_model_cv: k-NN
best_rmse_test: 5.705898064921308


In [ ]:
# Test 1 - P 1.5

In [ ]:
# Test 2 - P 1.5

1.6 - Con respecto al arbol de regresión, sería interesante determinar la importancia de las variables, es decir, que tan importante es cada variable en la predicción de la variable respuesta. Para ello, ajuste un árbol de regresión con profundidad máxima de 4 y número mínimo para realizar una partición en 20 (`max_depth=4`, `min_samples_split=20`) utilizando todas las variables explicativas. Luego, calcule la importancia de las variables utilizando el método `feature_importances_` del modelo ajustado. Finalmente, ordene las variables de mayor a menor importancia y seleccione las 5 variables más importantes. ¿Coinciden con las variables significativas del modelo de regresión lineal? (`p-value < 0.05`). Para responder esto último, debe ajustar un modelo de regresión lineal utilizando todas las variables explicativas (con intercepto) y luego calcular el p-value de cada variable del modelo ajustado.

Para esta pregunta, se espera que usted entregue un vector de largo 5 con los nombres de las variables más importantes. El nombre del vector debe ser `top5` y 
debe estar ordenado de mayor a menor importancia. Además, debe entregar un vector booleano de largo 5 con los valores `True` y `False` que indiquen si la variable correspondiente al vector `top5` es significativa en el modelo de regresión lineal. El nombre del vector debe ser `top5_significance`.

**Importante**: para esta pregunta, debe utilizar la semilla de aleatorización 123 como parámetro del modelo de árbol de regresión (`random_state=123`).

In [ ]:
top5 = None                     # Variable que debe modificar
top5_significance = None        # Variable que debe modificar

# your code here
raise NotImplementedError

In [31]:
tree_model = DecisionTreeRegressor(max_depth=4, min_samples_split=20, random_state=123)
tree_model.fit(X_train, y_train)

importances = tree_model.feature_importances_
importances_df = pd.DataFrame({
    'Variable': X_train.columns,
    'Importancia': importances
})
importances_df = importances_df.sort_values(by='Importancia', ascending=False)
top5 = importances_df.head(5)['Variable'].tolist()
print(f"Top 5 variables más importantes: {top5}")

X_train_sm = sm.add_constant(X_train)
lm_model = sm.OLS(y_train, X_train_sm).fit()
p_values = lm_model.pvalues
top5_significance = [p_values[var] < 0.05 for var in top5]

print(f"Significancia de las top 5 variables: {top5_significance}")


Top 5 variables más importantes: ['temp', 'ibt', 'ibh', 'dpg', 'vis']
Significancia de las top 5 variables: [True, False, False, False, False]


In [ ]:
# Test 1 - P 1.6

In [ ]:
# Test 2 - P 1.6

# Problema 2

Para esta segunda sección, se utilizará el conjunto de datos `prostate`. Este conjunto de datos contiene información sobre 97 pacientes con cáncer de próstata. Considere la variable respuesta como `svi` (seminal vesicle invasion). Esta variable indica si el cáncer se ha extendido a la vesícula seminal (1) o no (0). Las demás variables serán consideradas como variables explicativas. 

El objetivo es ajustar y comparar diferentes modelos de clasificación para predecir si el cáncer se ha extendido a la vesícula seminal o no. Para ello, se utilizarán los siguientes modelos:

- Regresión logística.
- k-NN.
- Árbol de clasificación.

Los datos se cargarán automáticamente en la siguiente celda, con el nombre `prostate_data`.

In [32]:
prostate_data = prostate.load()  # cargamos los datos del problema 2

In [33]:
prostate_data

lcavol  lweight  age      lbph  svi      lcp  gleason  pgg45     lpsa
0  -0.579819   2.7695   50 -1.386294    0 -1.38629        6      0 -0.43078
1  -0.994252   3.3196   58 -1.386294    0 -1.38629        6      0 -0.16252
2  -0.510826   2.6912   74 -1.386294    0 -1.38629        7     20 -0.16252
3  -1.203973   3.2828   58 -1.386294    0 -1.38629        6      0 -0.16252
4   0.751416   3.4324   62 -1.386294    0 -1.38629        6      0  0.37156
..       ...      ...  ...       ...  ...      ...      ...    ...      ...
92  2.830268   3.8764   68 -1.386294    1  1.32176        7     60  4.38515
93  3.821004   3.8969   44 -1.386294    1  2.16905        7     40  4.68444
94  2.907447   3.3962   52 -1.386294    1  2.46385        7     10  5.14312
95  2.882564   3.7739   68  1.558145    1  1.55814        7     80  5.47751
96  3.471967   3.9750   68  0.438255    1  2.90417        7     20  5.58293

[97 rows x 9 columns]

2.1 - Realizar una descomposición aleatoria estratificada (por la variable respuesta) de la base de datos con la proporción 70%-30% para train y test, respectivamente. Utilice el número 12345 como semilla de aleatorización. Esta descomposición estratificada es necesaria para que la proporción de 1's y 0's sea la misma en ambas particiones. Utilice el argumento `stratify` para crear la partición estratificada.

Guardar la información en los siguientes objetos:
- `train2`: partición de entrenamiento    (incluyendo todas las variables).
- `test2`: partición para la validacíon   (incluyendo todas las variables).

Recuerde respetar la semilla de aleatorización, la proporción de la partición y el nombre de los objetos. Además, utilice `train_test_split(prostate_data, ...)` para obtener de inmediato las particiones de entrenamiento y validación con todas las variables.

In [ ]:
train2 = None      # Variable que debe modificar
test2 = None       # Variable que debe modificar

# your code here
raise NotImplementedError

In [34]:
X = prostate_data.drop(columns='svi')
y = prostate_data['svi']
train2, test2 = train_test_split(prostate_data, test_size=0.3, random_state=12345, stratify=prostate_data['svi'])
print(f"Tamaño del conjunto de entrenamiento: {train2.shape}")
print(f"Tamaño del conjunto de prueba: {test2.shape}")


Tamaño del conjunto de entrenamiento: (67, 9)
Tamaño del conjunto de prueba: (30, 9)


In [ ]:
# Test 1 - P 2.1

In [ ]:
# Test 2 - P 2.1

2.2 - Utilizando la partición de entrenamiento (`train2`), ajuste los siguientes modelos:
- Regresión logística con intercepto (`fit_intercept=True`) y método de optimización `newton-cg` (`solver='newton-cg'`).
- k-NN con $k=10$ (`n_neighbors=10`) y utilizando como métrica la distancia euclidiana (`metric='euclidean'`). Para este modelo, además, normalice las variables utilizando el método min-max (`MinMaxScaler()`).
- Árbol de clasificación con profundidad máxima de 4 (`max_depth=4`) y número mínimo para realizar una partición en 10 (`min_samples_split=10`). Además, utilice como semilla de aleatorización el número 123 (`random_state=123`).

Luego de ajustar los modelos, calcule la exactitud (`accuracy`), sensibilidad (`recall`), presición (`precision`) y el $F_1\text{-}Score$ de cada uno de ellos sobre los datos de validación (`test2`).

Para esta pregunta, se espera que usted entregue un `data frame` de 3 filas y 4 columnas. Las filas corresponden a los modelos y las columnas corresponden a las métricas. Los nombres de las filas deben ser `logit`, `knn` y `dtree`, respectivamente. Los nombres de las columnas deben ser `accuracy`, `recall`, `precision` y `f1_score`, respectivamente.

El data frame debe llamarse `performance_metrics`.

Nota: para la clasificación de las observaciones, se debe utilizar el umbral de 0.5. Es decir, si la probabilidad de que la observación pertenezca a la clase 1 es mayor o igual a 0.5, entonces se clasifica como 1. En caso contrario, se clasifica como 0.

In [ ]:
performance_metrics = pd.DataFrame(columns=['accuracy', 'recall', 'precision', 'f1_score'], index=['logit', 'knn', 'dtree'])

# your code here
raise NotImplementedError

In [36]:
X_train2 = train2.drop(columns='svi')
y_train2 = train2['svi']
X_test2 = test2.drop(columns='svi')
y_test2 = test2['svi']

# regres
logit_model = LogisticRegression(fit_intercept=True, solver='newton-cg', random_state=12345)
logit_model.fit(X_train2, y_train2)
y_pred_logit = logit_model.predict(X_test2)

#knn
scaler = MinMaxScaler()
X_train2_scaled = scaler.fit_transform(X_train2)
X_test2_scaled = scaler.transform(X_test2)
knn_model = KNeighborsClassifier(n_neighbors=10, metric='euclidean')
knn_model.fit(X_train2_scaled, y_train2)
y_pred_knn = knn_model.predict(X_test2_scaled)

#arbol
dtree_model = DecisionTreeClassifier(max_depth=4, min_samples_split=10, random_state=123)
dtree_model.fit(X_train2, y_train2)
y_pred_dtree = dtree_model.predict(X_test2)

def compute_metrics(y_true, y_pred):
    return {
        'accuracy': metrics.accuracy_score(y_true, y_pred),
        'recall': metrics.recall_score(y_true, y_pred),
        'precision': metrics.precision_score(y_true, y_pred),
        'f1_score': metrics.f1_score(y_true, y_pred)
    }

metrics_logit = compute_metrics(y_test2, y_pred_logit)
metrics_knn = compute_metrics(y_test2, y_pred_knn)
metrics_dtree = compute_metrics(y_test2, y_pred_dtree)

performance_metrics = pd.DataFrame({
    'accuracy': [metrics_logit['accuracy'], metrics_knn['accuracy'], metrics_dtree['accuracy']],
    'recall': [metrics_logit['recall'], metrics_knn['recall'], metrics_dtree['recall']],
    'precision': [metrics_logit['precision'], metrics_knn['precision'], metrics_dtree['precision']],
    'f1_score': [metrics_logit['f1_score'], metrics_knn['f1_score'], metrics_dtree['f1_score']]
}, index=['logit', 'knn', 'dtree'])

print(performance_metrics)


       accuracy    recall  precision  f1_score
logit  0.900000  0.666667   0.800000  0.727273
knn    0.833333  0.500000   0.600000  0.545455
dtree  0.766667  0.500000   0.428571  0.461538


In [ ]:
# Test 1 - P 2.2

In [ ]:
# Test 2 - P 2.2

2.3 - En el contexto del problema anterior, la clasificación correcta de los pacientes en los cuales el cáncer se ha extendido a la vesícula seminal es más importante que la clasificación correcta de los pacientes en los cuales el cáncer no se ha extendido. Por lo tanto, es necesario ajustar los modelos de clasificación para que tengan un mejor desempeño en la clasificación de los pacientes en los cuales el cáncer se ha extendido a la vesícula seminal. Para ello, se utilizará la muestra de entrenamiento (`train2`) con la técnica de validación cruzada k-fold con $k=5$ para ajustar cada uno de los modelos de clasificación. Además, como es crucial detectar los casos positivos, se utilizará el $F_{\beta}$-score con $\beta=10$ como métrica de desempeño. De esta manera, se le dará más peso a la sensibilidad (`recall`). 

Se espera que usted entregue un `data frame` de 2 filas y 3 columnas. Las columnas corresponden a los modelos y las las filas corresponden a las métricas. Las métricas son el $F_{\beta}$-score promedio y la desviación estándar del $F_{\beta}$-score. Los nombres de las columnas deben ser `logit`, `knn` y `dtree`, respectivamente. Los nombres de las filas deben ser `f_score_mean` y `f_score_std`, respectivamente.

El data frame debe llamarse `f_score`.

**Nota**: utilizar la semilla de aleatorización 123 para el modelo de árbol de clasificación (`random_state=123`). Además, recordar utilizar `solver='newton-cg'` y `fit_intercept=True` para el modelo de regresión logística. Por último, utilizar `n_neighbors=10` y `metric='euclidean'` para el modelo de k-NN, y `max_depth=4` , `min_samples_split=10` para el modelo de árbol de clasificación.

Utilice la función `cross_val_score` para realizar la validación cruzada k-fold y dentro de la opción de la función `metrics.fbeta_score` utilizar `zero_division=0`.


In [ ]:
f_score = pd.DataFrame(columns=['logit', 'knn', 'dtree'], index=['f_score_mean', 'f_score_std'])

# your code here
raise NotImplementedError

In [37]:

X_train2 = train2.drop(columns='svi')
y_train2 = train2['svi']
logit_model = LogisticRegression(fit_intercept=True, solver='newton-cg', random_state=12345)
knn_model = KNeighborsClassifier(n_neighbors=10, metric='euclidean')
dtree_model = DecisionTreeClassifier(max_depth=4, min_samples_split=10, random_state=123)


def fbeta_scorer(model, X, y):
    return cross_val_score(model, X, y, cv=5, scoring=lambda est, X, y: metrics.fbeta_score(y, est.predict(X), beta=10, zero_division=0))

f_score_logit = fbeta_scorer(logit_model, X_train2, y_train2)
f_score_knn = fbeta_scorer(knn_model, X_train2, y_train2)
f_score_dtree = fbeta_scorer(dtree_model, X_train2, y_train2)
f_score = pd.DataFrame({
    'logit': [np.mean(f_score_logit), np.std(f_score_logit)],
    'knn': [np.mean(f_score_knn), np.std(f_score_knn)],
    'dtree': [np.mean(f_score_dtree), np.std(f_score_dtree)]
}, index=['f_score_mean', 'f_score_std'])

print(f_score)


                 logit  knn     dtree
f_score_mean  0.733775  0.0  0.533557
f_score_std   0.133115  0.0  0.339809


In [42]:
fbeta_scorer = metrics.make_scorer(metrics.fbeta_score, beta=10, zero_division=0)
logit_model = LogisticRegression(fit_intercept=True, solver='newton-cg', random_state=12345)
logit_scores = cross_val_score(logit_model, X_train2, y_train2, cv=5, scoring=fbeta_scorer)
scaler = MinMaxScaler()
X_train2_scaled = scaler.fit_transform(X_train2)
knn_model = KNeighborsClassifier(n_neighbors=10, metric='euclidean')
knn_scores = cross_val_score(knn_model, X_train2_scaled, y_train2, cv=5, scoring=fbeta_scorer)
dtree_model = DecisionTreeClassifier(max_depth=4, min_samples_split=10, random_state=123)
dtree_scores = cross_val_score(dtree_model, X_train2, y_train2, cv=5, scoring=fbeta_scorer)

f_score = pd.DataFrame({
    'logit': [logit_scores.mean(), logit_scores.std()],
    'knn': [knn_scores.mean(), knn_scores.std()],
    'dtree': [dtree_scores.mean(), dtree_scores.std()]
}, index=['f_score_mean', 'f_score_std'])

print(f_score)


                 logit       knn     dtree
f_score_mean  0.733775  0.533996  0.533557
f_score_std   0.133115  0.339979  0.339809


In [ ]:
# Test 1 - P 2.3

In [ ]:
# Test 2 - P 2.3

2.4 - Según los resultados obtenidos en la pregunta anterior, ¿qué modelo debería elegir?. 

Además, medir el error de generalización del modelo escogido mediante el accuracy.

Para responder esta pregunta, debe entregar un string con el nombre `best_model` que corresponda al nombre del modelo elegido, y un objeto con el nombre `best_accuracy` con el valor del accuracy como una medida de la generalización del modelo escogido. 

Los nombres de los modelos en el string pueden ser los
siguientes: "logit", "knn" y "dtree" para la regresión logística, k-NN y árbol de clasificación, respectivamente.

In [ ]:
best_model = None          # Variable que debe modificar
best_accuracy = None       # Variable que debe modificar

# your code here
raise NotImplementedError

In [39]:
best_model = LogisticRegression(fit_intercept=True, solver='newton-cg', random_state=12345)
best_model.fit(X_train2, y_train2)
X_test2 = test2.drop(columns='svi')
y_test2 = test2['svi']
y_pred = best_model.predict(X_test2)
best_accuracy = metrics.accuracy_score(y_test2, y_pred)
best_model_name = "logit"

print(f"Best Model: {best_model_name}")
print(f"Best Accuracy: {best_accuracy}")


Best Model: logit
Best Accuracy: 0.9


In [44]:
best_model = "logit"
logit_model.fit(X_train2, y_train2)
y_pred_best = logit_model.predict(X_test2)
best_accuracy = metrics.accuracy_score(y_test2, y_pred_best)

print(f"Best Model: {best_model}")
print(f"Best Accuracy: {best_accuracy}")


Best Model: logit
Best Accuracy: 0.9


In [ ]:
# Test 1 - P 2.4

In [ ]:
# Test 2 - P 2.4 